export const routes = {
  home: '/',
  about: '/about',
  contact: '/contact',
  allnews: '/allnews',
  hydrokol: '/hydrokol',
  tariff: '/tariff',
  hydrolw: '/hydrolw',
  hydrogi: '/hydrogi',
  hydrolub: '/hydrolub',
  download: '/download',
  rodo: '/rodo',
  cookies: '/cookies',
  oczyszczgi: '/oczyszczgi',
  oczyszczlub: '/oczyszczlub',
  oczyszczlw: '/oczyszczlw',
  oczyszczkol: '/oczyszczkol',
  wcag: '/wcag',
};
